version: '3.1'
services:
  db:
    image: postgres:14.1
    restart: always
    environment:
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: mydb
      POSTGRES_USER: johndoe
    ports:
      - "5432:5432"
